In [86]:
###                               ETL



#Extraction libreries
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.common.by import By
from selenium.webdriver.support.wait import WebDriverWait

#Transpose
import pandas as pd

#Load 
import sqlite3
from datetime import date
from openpyxl import load_workbook
import os
import wget
import time



import random
today = date.today()

In [87]:
def zoomin():
    driver.execute_script("document.body.style.zoom='125 %'")
    
def zoomout():
    driver.execute_script("document.body.style.zoom='90 %'")
    
def commentFinder(numComment):
    
    " numComment = 0 takes the head comment."
    
    if numComment == 0:
        return '/html/body/div[6]/div[2]/div/article/div[3]/div[1]/ul/div/li/div/div/div[2]'
    return '/html/body/div[6]/div[2]/div/article/div[3]/div[1]/ul/ul[{}]/div/li/div/div[1]/div[2]'.format(numComment)

In [88]:
#general photo scraping
def photoFinder(row,col):
    
    if col not in [1,2,3]:
        col = 3
        print('photo colum has been changed to 3 ')
    
    try:
        Xpath =  '//*[@id"react-root"]/section/main/div/div[4]/article/div[1]/div/div[{0}]/div[{1}]/a/div/div[2]'.format(row,col)
        buttonGrab(Xpath).click()
  
    except:
        Xpath =  '//*[@id="react-root"]/section/main/div/div[3]/article/div[1]/div/div[{0}]/div[{1}]/a/div/div[2]'.format(row,col)
        buttonGrab(Xpath).click()

In [89]:
path = r'C:\Users\97250\Desktop\studied\R ,python\chromedriver.exe'
driver = webdriver.Chrome(path)

In [90]:
driver.get("https://www.instagram.com/")
assert "Instagram" in driver.title

In [91]:
def buttonGrab(Xpath,kind = 'button'):
    
    if kind=='button':
        return WebDriverWait(driver,10).until(expected_conditions.element_to_be_clickable((By.XPATH, Xpath)))
    
    return WebDriverWait(driver,10).until(expected_conditions.element_to_be_selected((By.XPATH, Xpath)))

In [92]:
#the Facebook button
facebookXPath ='//*[@id="loginForm"]/div/div[5]/button/span[2]'
buttonGrab(facebookXPath).click()

In [93]:
# connecting to the database  
connection = sqlite3.connect("Scrpaer.db") 
# cursor  
crsr = connection.cursor()

In [94]:
##crsr.execute("ALTER TABLE user ADD site column_definition")
##crsr.execute("INSERT INTO user VALUES ('316408327','yanivm','makabi')")

sql = ("""UPDATE user
SET site = 'facebook'
WHERE username like '%7744%'""")

##crsr.execute(sql)

In [95]:
crsr.execute("SELECT * FROM user") 
fetched = crsr.fetchall()

In [96]:

connection.commit() 
connection.close()

In [97]:
username = buttonGrab('//*[@id="email"]')
password = buttonGrab('//*[@id="pass"]')
login =    buttonGrab('//*[@id="loginbutton"]')

In [98]:
username.clear()
password.clear()

username.send_keys(fetched[0][0])
password.send_keys(fetched[0][1])

login.click()

In [99]:
#click not now ver 2
notNowXPath = '/html/body/div[4]/div/div/div/div[3]/button[2]'
buttonGrab(notNowXPath).click()

In [100]:
searchBoxXpath = '//*[@id="react-root"]/section/nav/div[2]/div/div/div[2]/input'

def findresult(numResult=1):
    #'//*[@id="react-root"]/section/nav/div[2]/div/div/div[2]/div[3]/div[2]/div/a[1]/div/div[2]/div/span'
    return '//*[@id="react-root"]/section/nav/div[2]/div/div/div[2]/div[4]/div/a[1]/div/div[2]/div/span'
    
    # '//*[@id="react-root"]/section/nav/div[2]/div/div/div[2]/div[3]/div[2]/div/a['+str(numResult)+']/div/div[2]/div/span'

In [101]:
def searcher(numResult=1):
    
    searchBox = buttonGrab(searchBoxXpath)
    searchBox.clear()
    searchBox.send_keys(person)
    
    resultXpath = findresult(numResult)
    
    buttonGrab(resultXpath).click()
    time.sleep(2)

In [102]:

def scrapData():
    
    
    """
    scarps data
    """
    
    nameXpath      = '//*[@id="react-root"]/section/main/div/header/section/div[1]/h2'
    followersXpath = '//*[@id="react-root"]/section/main/div/header/section/ul/li[2]/a/span'
    followingXpath = '//*[@id="react-root"]/section/main/div/header/section/ul/li[3]/a/span'
    numPostsXpath  = '//*[@id="react-root"]/section/main/div/header/section/ul/li[1]/span/span'
    
    name = buttonGrab(nameXpath).text
    followers = buttonGrab(followersXpath).text
    following = buttonGrab(followingXpath).text
    numPosts  = buttonGrab(numPostsXpath).text
    
    
    return [person,following,followers,numPosts,name] 
    
    ###    MUST BE CHANGED SOON   !!!
    
    ##return [person,numPosts,following,followers,name]

In [103]:
InstaPeople = ['melaniekroll','leelevi','margauxdietz','hollyjboo','neleburgemstr','annabelsmitt','franziskakch','juliehocke','elletrowbridge','gracey_hodge','adi_hashamonai','shirifineman','marion.pascale','lylianawray','charleenweiss','miss_gemma_fied','talya_naftali','melissa_ran']
data = []
validation = []

In [104]:

    
for person in InstaPeople:

    searcher(person)
    
    try:
        data.append(scrapData()[:-1])

        # Validation
        if scrapData()[-1] != person:
            validation.append(person)

    except:
        pass

    if person[0] in ['lm']:
        
        try:
            photoFinder(1,3)
            text.append(buttonGrab(commentFinder(3),kind = '').text)
            zoomin()
            time.sleep(5)
            zoomout()
    except:
        pass

In [105]:
if len(validation) != 0:
    print(validation)

In [106]:
#   This model alwaus stuvk

##cassThor =['cass.thor','491','32.2k','1,954']
##idx = data.index(['marion.pascale', '880', '124k', '275']) + 1
##data.insert(idx,cassThor)

In [125]:
data

[['melaniekroll', '199', '209k', '560'],
 ['leelevi', '2,500', '146k', '2,582'],
 ['margauxdietz', '2,674', '405k', '3,159'],
 ['hollyjboo', '975', '51.4k', '1,132'],
 ['neleburgemstr', '2,676', '36.6k', '447'],
 ['annabelsmitt', '3,256', '139k', '1,820'],
 ['franziskakch', '611', '131k', '898'],
 ['juliehocke', '924', '116k', '1,403'],
 ['elletrowbridge', '1,451', '243k', '465'],
 ['gracey_hodge', '813', '184k', '650'],
 ['adi_hashamonai', '354', '98.3k', '5,516'],
 ['shirifineman', '183', '8,602', '56'],
 ['marion.pascale', '882', '125k', '276'],
 ['lylianawray', '143', '190k', '682'],
 ['charleenweiss', '311', '203k', '557'],
 ['miss_gemma_fied', '768', '76.2k', '576'],
 ['talya_naftali', '232', '2,168', '247'],
 ['melissa_ran', '673', '21.9k', '1,496']]

In [130]:
dataWorkFlow = data.copy() 
dataWorkFlow = pd.DataFrame(dataWorkFlow,columns = ['person','following','followers','numPosts'])
dataWorkFlow = dataWorkFlow.set_index('person')

In [131]:
def convertor(x):
    
    def remover(x):
        x = x.replace('k','').replace('m','').replace(',','')
        return float(x)
    
    x = str(x)
    
    if 'k' in x:
        return int(remover(x)*1000)
        
    if 'm' in x:
        return int(remover(x)*1000000)
    
    else:
        return int(remover(x))

dataWorkFlow['followers'] = dataWorkFlow['followers'].apply(convertor)
dataWorkFlow['following'] = dataWorkFlow['following'].apply(convertor)
dataWorkFlow['numPosts']  = dataWorkFlow['numPosts'].apply(convertor)

In [132]:
dataWorkFlow

                 following  followers  numPosts
person
melaniekroll           199     209000       560
leelevi               2500     146000      2582
margauxdietz          2674     405000      3159
hollyjboo              975      51400      1132
neleburgemstr         2676      36600       447
annabelsmitt          3256     139000      1820
franziskakch           611     131000       898
juliehocke             924     116000      1403
elletrowbridge        1451     243000       465
gracey_hodge           813     184000       650
adi_hashamonai         354      98300      5516
shirifineman           183       8602        56
marion.pascale         882     125000       276
lylianawray            143     190000       682
charleenweiss          311     203000       557
miss_gemma_fied        768      76200       576
talya_naftali          232       2168       247
melissa_ran            673      21900      1496

In [111]:
# Saving datas to ExcelSheet

path = r'C:\Users\97250\Desktop\studied\R ,python\InstaScraping.xlsx'
book = load_workbook(path)

### checks if no sheet from today
last_sheet_name = book.get_sheet_names()[-1]
if last_sheet_name == str(today) :
    last_sheet = book.get_sheet_by_name(last_sheet_name)
    book.remove_sheet(last_sheet)

writer = pd.ExcelWriter(path, engine = 'openpyxl')
writer.book = book    

#the sheet name will be the str(current date)
dataWorkFlow.to_excel(writer ,sheet_name = str(today)) 


writer.save()
writer.close()

<ipython-input-111-d7b78f222ece>:7: DeprecationWarning: Call to deprecated function get_sheet_names (Use wb.sheetnames).
  last_sheet_name = book.get_sheet_names()[-1]

In [129]:
# Saving datas to ExcelSheet

path = r'C:\Users\97250\Desktop\studied\R ,python\InstaScraping_afterManipulation.xlsx'
book = load_workbook(path)

### checks if no sheet from today
last_sheet_name = book.get_sheet_names()[-1]
if last_sheet_name == str(today) :
    last_sheet = book.get_sheet_by_name(last_sheet_name)
    book.remove_sheet(last_sheet)

writer = pd.ExcelWriter(path, engine = 'openpyxl')
writer.book = book    

#the sheet name will be the str(current date)
dataWorkFlow.to_excel(writer ,sheet_name = str(today)) 


writer.save()
writer.close()

<ipython-input-129-e860f54170c7>:7: DeprecationWarning: Call to deprecated function get_sheet_names (Use wb.sheetnames).
  last_sheet_name = book.get_sheet_names()[-1]

In [112]:
today = pd.to_datetime(today).date()
dataWorkFlow['date'] = today

In [113]:
dataWorkFlow = dataWorkFlow.reset_index().values.tolist()

In [114]:
###    SQL 
 
# connecting to the database  
connection = sqlite3.connect("Scrpaer.db") 
# cursor  
crsr = connection.cursor()

In [115]:

# create table 
sql = """CREATE TABLE instagram (  
name PRIMARY_KEY VARCHAR(25),
following VARCHAR(6),  
followers VARCHAR(6),  
numPosts VARCHAR(6),
date DATE
);"""

##crsr.execute(sql) 

##crsr.execute("drop table Instagram")

In [116]:
# SQL command to insert the data in the table 
sql = "INSERT INTO Instagram VALUES (?, ?, ?, ?, ?)"

#insert all values
connection.executemany(sql, dataWorkFlow)

In [117]:

crsr.execute("SELECT * FROM instagram")  
##crsr.execute("SELECT * FROM instagram where name like \"%b%\"")  
##crsr.execute("SELECT date FROM instagram")  
##crsr.execute("SELECT * FROM instagram GROUP BY name HAVING count(*)>1")  
##crsr.execute("SELECT name,AVG(followers) FROM instagram GROUP BY name ")  

sql = """select  
(count(followers)*sum(followers*followers) - (sum(followers)*sum(followers)))/((count(followers))*(count(followers))) as variance
from instagram 
"""
#crsr.execute(sql)

In [118]:
# store all the fetched data in 'ans' variable 
fetched = crsr.fetchall()    
print(len(fetched))

263

In [119]:

connection.commit() 
connection.close()

In [120]:
pd.DataFrame(fetched,columns=['person','following','followers','numPosts','date']).set_index('person')

                following followers numPosts        date
person
melaniekroll          199      175k      545  2020-10-31
leelevi             2,497      147k    2,564  2020-10-31
margauxdietz        2,655      405k    3,153  2020-10-31
neleburgemstr       2,723     36.6k      440  2020-10-31
annabelsmitt        3,237      136k    1,811  2020-10-31
...                   ...       ...      ...         ...
lylianawray           143    190000      682  2020-11-14
charleenweiss         311    203000      557  2020-11-14
miss_gemma_fied       768     76200      576  2020-11-14
talya_naftali         232      2168      247  2020-11-14
melissa_ran           673     21900     1496  2020-11-14

[263 rows x 4 columns]

###    THIS CODE IS FOR UPDATING COLUMNS INSIDE THE SQL DATABASE



sql = """ALTER TABLE instagram
RENAME COLUMN numPosts TO following1;"""

crsr.execute(sql)

sql = """ALTER TABLE instagram
RENAME COLUMN following TO numPosts;"""

crsr.execute(sql)

sql = """ALTER TABLE instagram
RENAME COLUMN following1 TO following;"""

crsr.execute(sql)

In [133]:
fetched

[('melaniekroll', '199', '175k', '545', '2020-10-31'),
 ('leelevi', '2,497', '147k', '2,564', '2020-10-31'),
 ('margauxdietz', '2,655', '405k', '3,153', '2020-10-31'),
 ('neleburgemstr', '2,723', '36.6k', '440', '2020-10-31'),
 ('annabelsmitt', '3,237', '136k', '1,811', '2020-10-31'),
 ('melaniekroll', '199', '176k', '546', '2020-10-31'),
 ('leelevi', '2,496', '147k', '2,564', '2020-10-31'),
 ('margauxdietz', '2,655', '405k', '3,153', '2020-10-31'),
 ('neleburgemstr', '2,527', '36.6k', '440', '2020-10-31'),
 ('annabelsmitt', '3,237', '136k', '1,811', '2020-10-31'),
 ('franziskakch', '601', '131k', '886', '2020-10-31'),
 ('juliehocke', '921', '115k', '1,394', '2020-10-31'),
 ('marion.pascale', '864', '119k', '282', '2020-10-31'),
 ('cass.thor', '1,949', '32.1k', '491', '2020-10-31'),
 ('lylianawray', '143', '176k', '679', '2020-10-31'),
 ('charleenweiss', '304', '202k', '553', '2020-10-31'),
 ('miss_gemma_fied', '772', '75.9k', '572', '2020-10-31'),
 ('talya_naftali', '231', '2,160', '247', '2020-10-31'),
 ('melaniekroll', '199', '179k', '546', '2020-11-01'),
 ('leelevi', '2,497', '147k', '2,564', '2020-11-01'),
 ('margauxdietz', '2,656', '406k', '3,153', '2020-11-01'),
 ('neleburgemstr', '2,625', '36.6k', '440', '2020-11-01'),
 ('annabelsmitt', '3,238', '136k', '1,812', '2020-11-01'),
 ('franziskakch', '601', '131k', '886', '2020-11-01'),
 ('juliehocke', '921', '115k', '1,395', '2020-11-01'),
 ('marion.pascale', '864', '119k', '271', '2020-11-01'),
 ('cass.thor', '1,949', '32.1k', '491', '2020-11-01'),
 ('lylianawray', '143', '176k', '679', '2020-11-01'),
 ('charleenweiss', '305', '202k', '553', '2020-11-01'),
 ('miss_gemma_fied', '772', '75.9k', '573', '2020-11-01'),
 ('talya_naftali', '231', '2,160', '247', '2020-11-01'),
 ('melissa_ran', '231', '2,160', '247', '2020-11-01'),
 ('melaniekroll', '199', '180000', '547', '2020-11-02'),
 ('leelevi', '2496', '147000', '2567', '2020-11-02'),
 ('margauxdietz', '2655', '406000', '3153', '2020-11-02'),
 ('neleburgemstr', '2301', '36600', '440', '2020-11-02'),
 ('annabelsmitt', '3242', '136000', '1812', '2020-11-02'),
 ('franziskakch', '603', '131000', '887', '2020-11-02'),
 ('juliehocke', '920', '115000', '1395', '2020-11-02'),
 ('marion.pascale', '864', '119000', '271', '2020-11-02'),
 ('cass.thor', '1951', '32100', '491', '2020-11-02'),
 ('lylianawray', '143', '176000', '679', '2020-11-02'),
 ('charleenweiss', '305', '202000', '554', '2020-11-02'),
 ('miss_gemma_fied', '772', '75900', '573', '2020-11-02'),
 ('talya_naftali', '231', '2160', '247', '2020-11-02'),
 ('melissa_ran', '668', '21700', '1483', '2020-11-02'),
 ('melaniekroll', '199', '182000', '548', '2020-11-03'),
 ('leelevi', '2498', '147000', '2567', '2020-11-03'),
 ('margauxdietz', '2657', '405000', '3154', '2020-11-03'),
 ('hollyjboo', '969', '51500', '1132', '2020-11-03'),
 ('neleburgemstr', '2391', '36600', '441', '2020-11-03'),
 ('annabelsmitt', '3238', '136000', '1813', '2020-11-03'),
 ('franziskakch', '605', '131000', '888', '2020-11-03'),
 ('juliehocke', '921', '115000', '1397', '2020-11-03'),
 ('marion.pascale', '869', '120000', '272', '2020-11-03'),
 ('cass.thor', '1949', '32100', '491', '2020-11-03'),
 ('lylianawray', '143', '177000', '680', '2020-11-03'),
 ('charleenweiss', '304', '202000', '554', '2020-11-03'),
 ('miss_gemma_fied', '772', '75900', '574', '2020-11-03'),
 ('talya_naftali', '231', '2160', '247', '2020-11-03'),
 ('melissa_ran', '669', '21700', '1485', '2020-11-03'),
 ('melaniekroll', '200', '184000', '550', '2020-11-04'),
 ('leelevi', '2496', '147000', '2570', '2020-11-04'),
 ('margauxdietz', '2658', '405000', '3154', '2020-11-04'),
 ('hollyjboo', '971', '51500', '1132', '2020-11-04'),
 ('neleburgemstr', '2483', '36600', '441', '2020-11-04'),
 ('annabelsmitt', '3238', '137000', '1814', '2020-11-04'),
 ('franziskakch', '605', '131000', '889', '2020-11-04'),
 ('juliehocke', '921', '115000', '1397', '2020-11-04'),
 ('marion.pascale', '875', '121000', '272', '2020-11-04'),
 ('cass.thor', '1953', '32100', '491', '2020-11-04'),
 ('lylianawray', '143', '177000', '680', '2020-11-04'),
 ('charleenweiss', '304', '202000', '554', '2020-11-04'),
 ('miss_gemma_fied', '772', '76000', '574', '2020-11-04'),
 ('talya_naftali', '231', '2158', '247', '2020-11-04'),
 ('melissa_ran', '669', '21800', '1486', '2020-11-04'),
 ('melaniekroll', '198', '187000', '550', '2020-11-05'),
 ('melaniekroll', '198', '187000', '550', '2020-11-05'),
 ('leelevi', '2496', '147000', '2570', '2020-11-05'),
 ('margauxdietz', '2660', '406000', '3154', '2020-11-05'),
 ('hollyjboo', '971', '51500', '1132', '2020-11-05'),
 ('neleburgemstr', '2331', '36600', '442', '2020-11-05'),
 ('annabelsmitt', '3237', '137000', '1814', '2020-11-05'),
 ('franziskakch', '606', '131000', '889', '2020-11-05'),
 ('juliehocke', '921', '115000', '1397', '2020-11-05'),
 ('marion.pascale', '876', '121000', '272', '2020-11-05'),
 ('cass.thor', '1954', '32100', '491', '2020-11-05'),
 ('lylianawray', '143', '177000', '680', '2020-11-05'),
 ('charleenweiss', '305', '202000', '554', '2020-11-05'),
 ('miss_gemma_fied', '772', '76000', '574', '2020-11-05'),
 ('talya_naftali', '231', '2159', '247', '2020-11-05'),
 ('melissa_ran', '669', '21800', '1486', '2020-11-05'),
 ('melaniekroll', '198', '191000', '551', '2020-11-06'),
 ('leelevi', '2496', '147000', '2570', '2020-11-06'),
 ('margauxdietz', '2661', '406000', '3154', '2020-11-06'),
 ('hollyjboo', '969', '51500', '1132', '2020-11-06'),
 ('neleburgemstr', '2567', '36600', '442', '2020-11-06'),
 ('annabelsmitt', '3237', '137000', '1814', '2020-11-06'),
 ('franziskakch', '607', '131000', '890', '2020-11-06'),
 ('juliehocke', '921', '115000', '1398', '2020-11-06'),
 ('marion.pascale', '879', '122000', '272', '2020-11-06'),
 ('cass.thor', '1955', '32100', '491', '2020-11-06'),
 ('lylianawray', '143', '177000', '680', '2020-11-06'),
 ('charleenweiss', '304', '202000', '554', '2020-11-06'),
 ('miss_gemma_fied', '772', '76100', '574', '2020-11-06'),
 ('talya_naftali', '231', '2158', '247', '2020-11-06'),
 ('melissa_ran', '669', '21800', '1487', '2020-11-06'),
 ('melaniekroll', '198', '195000', '552', '2020-11-07'),
 ('leelevi', '2495', '147000', '2570', '2020-11-07'),
 ('margauxdietz', '2662', '406000', '3155', '2020-11-07'),
 ('hollyjboo', '971', '51500', '1132', '2020-11-07'),
 ('neleburgemstr', '2586', '36600', '443', '2020-11-07'),
 ('annabelsmitt', '3239', '137000', '1815', '2020-11-07'),
 ('franziskakch', '607', '131000', '890', '2020-11-07'),
 ('juliehocke', '922', '115000', '1399', '2020-11-07'),
 ('marion.pascale', '879', '122000', '272', '2020-11-07'),
 ('cass.thor', '1954', '32100', '491', '2020-11-07'),
 ('lylianawray', '143', '178000', '681', '2020-11-07'),
 ('charleenweiss', '304', '202000', '554', '2020-11-07'),
 ('miss_gemma_fied', '772', '76100', '574', '2020-11-07'),
 ('talya_naftali', '231', '2158', '247', '2020-11-07'),
 ('melissa_ran', '669', '21800', '1487', '2020-11-07'),
 ('melaniekroll', '198', '198000', '553', '2020-11-08'),
 ('leelevi', '2494', '147000', '2570', '2020-11-08'),
 ('margauxdietz', '2662', '406000', '3155', '2020-11-08'),
 ('hollyjboo', '973', '51500', '1132', '2020-11-08'),
 ('neleburgemstr', '2597', '36600', '443', '2020-11-08'),
 ('annabelsmitt', '3243', '137000', '1815', '2020-11-08'),
 ('franziskakch', '607', '131000', '892', '2020-11-08'),
 ('juliehocke', '923', '116000', '1399', '2020-11-08'),
 ('marion.pascale', '881', '122000', '273', '2020-11-08'),
 ('cass.thor', '1952', '32100', '491', '2020-11-08'),
 ('lylianawray', '143', '180000', '681', '2020-11-08'),
 ('charleenweiss', '304', '202000', '554', '2020-11-08'),
 ('miss_gemma_fied', '772', '76200', '574', '2020-11-08'),
 ('talya_naftali', '230', '2157', '247', '2020-11-08'),
 ('melissa_ran', '669', '21800', '1487', '2020-11-08'),
 ('melaniekroll', '196', '201000', '555', '2020-11-09'),
 ('leelevi', '2497', '147000', '2573', '2020-11-09'),
 ('margauxdietz', '2661', '406000', '3155', '2020-11-09'),
 ('hollyjboo', '973', '51500', '1132', '2020-11-09'),
 ('neleburgemstr', '2474', '36600', '443', '2020-11-09'),
 ('annabelsmitt', '3244', '137000', '1816', '2020-11-09'),
 ('franziskakch', '609', '131000', '894', '2020-11-09'),
 ('juliehocke', '922', '116000', '1399', '2020-11-09'),
 ('marion.pascale', '886', '122000', '274', '2020-11-09'),
 ('cass.thor', '1952', '32100', '491', '2020-11-09'),
 ('lylianawray', '143', '181000', '681', '2020-11-09'),
 ('charleenweiss', '306', '202000', '555', '2020-11-09'),
 ('miss_gemma_fied', '575', '76200', '769', '2020-11-09'),
 ('talya_naftali', '247', '2157', '230', '2020-11-09'),
 ('melissa_ran', '1490', '21800', '669', '2020-11-09'),
 ('melaniekroll', '196', '203000', '556', '2020-11-10'),
 ('leelevi', '2499', '147000', '2576', '2020-11-10'),
 ('margauxdietz', '2661', '406000', '3155', '2020-11-10'),
 ('hollyjboo', '973', '51500', '1132', '2020-11-10'),
 ('neleburgemstr', '2760', '36600', '445', '2020-11-10'),
 ('annabelsmitt', '3249', '138000', '1817', '2020-11-10'),
 ('franziskakch', '607', '131000', '895', '2020-11-10'),
 ('juliehocke', '923', '116000', '1399', '2020-11-10'),
 ('elletrowbridge', '1446', '242000', '463', '2020-11-10'),
 ('gracey_hodge', '798', '185000', '648', '2020-11-10'),
 ('adi_hashamonai', '354', '98300', '5512', '2020-11-10'),
 ('shirifineman', '186', '8647', '56', '2020-11-10'),
 ('marion.pascale', '887', '123000', '275', '2020-11-10'),
 ('cass.thor', '491', '32100', '1952', '2020-11-10'),
 ('lylianawray', '143', '183000', '681', '2020-11-10'),
 ('charleenweiss', '308', '203000', '555', '2020-11-10'),
 ('miss_gemma_fied', '767', '76300', '576', '2020-11-10'),
 ('talya_naftali', '230', '2170', '247', '2020-11-10'),
 ('melissa_ran', '669', '21900', '1491', '2020-11-10'),
 ('melaniekroll', '196', '205000', '556', '2020-11-11'),
 ('leelevi', '2499', '147000', '2579', '2020-11-11'),
 ('margauxdietz', '2663', '406000', '3156', '2020-11-11'),
 ('hollyjboo', '974', '51500', '1132', '2020-11-11'),
 ('neleburgemstr', '2679', '36600', '445', '2020-11-11'),
 ('annabelsmitt', '3253', '138000', '1817', '2020-11-11'),
 ('franziskakch', '608', '131000', '896', '2020-11-11'),
 ('juliehocke', '923', '116000', '1400', '2020-11-11'),
 ('elletrowbridge', '1448', '242000', '463', '2020-11-11'),
 ('gracey_hodge', '800', '185000', '648', '2020-11-11'),
 ('adi_hashamonai', '354', '98400', '5512', '2020-11-11'),
 ('shirifineman', '186', '8648', '56', '2020-11-11'),
 ('marion.pascale', '887', '124000', '275', '2020-11-11'),
 ('cass.thor', '491', '32100', '1955', '2020-11-11'),
 ('lylianawray', '143', '184000', '682', '2020-11-11'),
 ('charleenweiss', '308', '203000', '555', '2020-11-11'),
 ('miss_gemma_fied', '768', '76200', '576', '2020-11-11'),
 ('talya_naftali', '231', '2171', '247', '2020-11-11'),
 ('melissa_ran', '670', '21900', '1492', '2020-11-11'),
 ('melaniekroll', '197', '207000', '558', '2020-11-12'),
 ('leelevi', '2500', '146000', '2582', '2020-11-12'),
 ('margauxdietz', '2669', '405000', '3157', '2020-11-12'),
 ('hollyjboo', '974', '51400', '1132', '2020-11-12'),
 ('neleburgemstr', '2527', '36600', '445', '2020-11-12'),
 ('annabelsmitt', '3254', '138000', '1819', '2020-11-12'),
 ('franziskakch', '609', '131000', '896', '2020-11-12'),
 ('juliehocke', '924', '116000', '1401', '2020-11-12'),
 ('elletrowbridge', '1449', '243000', '464', '2020-11-12'),
 ('gracey_hodge', '804', '184000', '649', '2020-11-12'),
 ('adi_hashamonai', '352', '98300', '5514', '2020-11-12'),
 ('shirifineman', '186', '8648', '56', '2020-11-12'),
 ('marion.pascale', '880', '124000', '275', '2020-11-12'),
 ('cass.thor', '491', '32200', '1954', '2020-11-12'),
 ('lylianawray', '143', '186000', '682', '2020-11-12'),
 ('charleenweiss', '308', '203000', '557', '2020-11-12'),
 ('miss_gemma_fied', '768', '76300', '576', '2020-11-12'),
 ('talya_naftali', '232', '2166', '247', '2020-11-12'),
 ('melissa_ran', '670', '21900', '1493', '2020-11-12'),
 ('melaniekroll', '199', '208000', '558', '2020-11-13'),
 ('leelevi', '2497', '146000', '2582', '2020-11-13'),
 ('margauxdietz', '2671', '405000', '3158', '2020-11-13'),
 ('hollyjboo', '974', '51400', '1132', '2020-11-13'),
 ('neleburgemstr', '974', '51400', '1132', '2020-11-13'),
 ('annabelsmitt', '3254', '138000', '1819', '2020-11-13'),
 ('franziskakch', '611', '131000', '898', '2020-11-13'),
 ('juliehocke', '924', '116000', '1402', '2020-11-13'),
 ('elletrowbridge', '1450', '243000', '465', '2020-11-13'),
 ('gracey_hodge', '808', '184000', '650', '2020-11-13'),
 ('adi_hashamonai', '353', '98300', '5515', '2020-11-13'),
 ('shirifineman', '184', '8610', '56', '2020-11-13'),
 ('marion.pascale', '881', '125000', '275', '2020-11-13'),
 ('lylianawray', '143', '188000', '682', '2020-11-13'),
 ('charleenweiss', '311', '203000', '557', '2020-11-13'),
 ('miss_gemma_fied', '768', '76200', '576', '2020-11-13'),
 ('talya_naftali', '231', '2169', '247', '2020-11-13'),
 ('melissa_ran', '672', '21900', '1494', '2020-11-13'),
 ('melaniekroll', '199', '208000', '558', '2020-11-13'),
 ('leelevi', '2497', '146000', '2582', '2020-11-13'),
 ('margauxdietz', '2671', '405000', '3158', '2020-11-13'),
 ('hollyjboo', '974', '51400', '1132', '2020-11-13'),
 ('neleburgemstr', '974', '51400', '1132', '2020-11-13'),
 ('annabelsmitt', '3254', '138000', '1819', '2020-11-13'),
 ('franziskakch', '611', '131000', '898', '2020-11-13'),
 ('juliehocke', '924', '116000', '1402', '2020-11-13'),
 ('elletrowbridge', '1450', '243000', '465', '2020-11-13'),
 ('gracey_hodge', '808', '184000', '650', '2020-11-13'),
 ('adi_hashamonai', '353', '98300', '5515', '2020-11-13'),
 ('shirifineman', '184', '8610', '56', '2020-11-13'),
 ('marion.pascale', '881', '125000', '275', '2020-11-13'),
 ('lylianawray', '143', '188000', '682', '2020-11-13'),
 ('charleenweiss', '311', '203000', '557', '2020-11-13'),
 ('miss_gemma_fied', '768', '76200', '576', '2020-11-13'),
 ('talya_naftali', '231', '2169', '247', '2020-11-13'),
 ('melissa_ran', '672', '21900', '1494', '2020-11-13'),
 ('melaniekroll', '199', '209000', '560', '2020-11-14'),
 ('leelevi', '2500', '146000', '2582', '2020-11-14'),
 ('margauxdietz', '2674', '405000', '3159', '2020-11-14'),
 ('hollyjboo', '975', '51400', '1132', '2020-11-14'),
 ('neleburgemstr', '2676', '36600', '447', '2020-11-14'),
 ('annabelsmitt', '3256', '139000', '1820', '2020-11-14'),
 ('franziskakch', '611', '131000', '898', '2020-11-14'),
 ('juliehocke', '924', '116000', '1403', '2020-11-14'),
 ('elletrowbridge', '1451', '243000', '465', '2020-11-14'),
 ('gracey_hodge', '813', '184000', '650', '2020-11-14'),
 ('adi_hashamonai', '354', '98300', '5516', '2020-11-14'),
 ('shirifineman', '183', '8602', '56', '2020-11-14'),
 ('marion.pascale', '882', '125000', '276', '2020-11-14'),
 ('lylianawray', '143', '190000', '682', '2020-11-14'),
 ('charleenweiss', '311', '203000', '557', '2020-11-14'),
 ('miss_gemma_fied', '768', '76200', '576', '2020-11-14'),
 ('talya_naftali', '232', '2168', '247', '2020-11-14'),
 ('melissa_ran', '673', '21900', '1496', '2020-11-14')]

In [ ]:
####     IT'S REQUIRED TO CHANGE NELEBURGSTER DATA

In [ ]:
####     AS OF THE 13.11 IN SQL DATABASE TO THE RIGHT VALUES!!!

In [ ]:
####   + VERIFICATION IN CASE OF SCRAPING THE WRONG WAY  !